"""empty message

Revision ID: 0520d199e894
Revises: 3910c60c289d
Create Date: 2019-07-26 13:19:26.469144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0520d199e894'
down_revision = '3910c60c289d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('Users', 'data_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('data_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'date_updated')
    # ### end Alembic commands ###
