"""empty message

Revision ID: 71f738930896
Revises: fa92e6af2b3c
Create Date: 2019-07-29 10:37:06.711263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f738930896'
down_revision = 'fa92e6af2b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('project_creator', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_creator'], ['Users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_owner'], ['Accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('task_creator', sa.Integer(), nullable=False),
    sa.Column('task_assigned', sa.Integer(), nullable=False),
    sa.Column('project_task_belong', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_task_belong'], ['Projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_assigned'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['task_creator'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Users', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('Users', sa.Column('status', sa.VARCHAR(length=20), nullable=False))
    op.create_foreign_key(None, 'Users', 'Accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'status')
    op.drop_column('Users', 'account_id')
    op.drop_table('attachment')
    op.drop_table('tasks')
    op.drop_table('Projects')
    op.drop_table('Accounts')
    # ### end Alembic commands ###
