"""empty message

Revision ID: 835f55bb1578
Revises: 67d3e2146f8f
Create Date: 2019-07-26 11:44:51.802586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835f55bb1578'
down_revision = '67d3e2146f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password_hash', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password_hash')
    # ### end Alembic commands ###
