"""empty message

Revision ID: 8d1e67099208
Revises: 71f738930896
Create Date: 2019-07-29 11:59:39.043190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1e67099208'
down_revision = '71f738930896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
