"""empty message

Revision ID: fa92e6af2b3c
Revises: 0520d199e894
Create Date: 2019-07-26 13:19:42.904597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa92e6af2b3c'
down_revision = '0520d199e894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('Users', 'data_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('data_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'date_updated')
    # ### end Alembic commands ###
